### ISSUE TITLE
No peaks found in image upon repeating the registration analysis

### ISSUE THREAD

**Issue by NadiaHuisjes** [fiji/Descriptor_based_registration#6]
Dear writers,

First of all, thank you for this great plugin. It is of much help to my data analysis :)
I encountered the following. When I run the 'descriptor based registration (2d/3d)' plugin on my data and apply relevant settings it finds the Affine2D matrix correctly. However, when I subsequently close the overlap image and the log window, then try to repeat the analysis on the same images again, it always returns an error in the log stating that no peaks were found. (see screenshot below). Closing and reopening the images usually resolves the issue. Perhaps it stores the ROIs from my previous analysis and that causes problems in the filtering step. Might this be a bug in the code? Or is this behaviour as expected and should I just reopen my images before using the tool again?

<img width="1042" alt="Screenshot 2021-05-25 at 12 24 51" src="https://user-images.githubusercontent.com/61824826/119483019-d433d000-bd54-11eb-8dc7-8f472c819de4.png">

Thank you in advance!
Nadia

**Comment by imagejan** [comment]
Did you choose the option to show a point selection of the corresponding peaks? If so, try to remove the selection before re-running the plugin. Otherwise it'll try to detect spots within the current selection only, which might result in the behavior you're seeing.

**Comment by NadiaHuisjes** [comment]
Thank you for your reply! This helped me a lot :-)
The next time I will take a look at the forum first.
